/**
 * Turning changed files into technology tags.
 *
 * The failure mode this module exists to prevent has a name in the market:
 * CodersRank ranked people in the top few percent of languages they had never
 * written, because it inferred language from the bytes sitting in a repository
 * rather than from the lines a person actually changed. Vendored dependencies,
 * lockfiles and generated clients are enormous and they are nobody's work.
 *
 * So the rule here is narrow on purpose: a technology is credited only when the
 * user changed a file that (a) is not excluded below and (b) has an extension
 * this module recognises. Anything unrecognised contributes nothing — silence
 * is the safe default when the alternative is a claim on a CV.
 */

/**
 * Paths that must never influence a technology tag, with the reason each one is
 * here. Exported so the README's claims are checkable and the tests can assert
 * against the real list rather than a copy of it.
 *
 * Matched against the repo-relative POSIX path of a changed file.
 */
export const EXCLUDED_PATH_PATTERNS: ReadonlyArray<{
  readonly pattern: RegExp;
  readonly why: string;
}> = [
  // --- Dependency trees checked into the repo -----------------------------
  {
    pattern: /(^|\/)node_modules\//,
    why: "npm dependency tree — someone else's code",
  },
  {
    pattern: /(^|\/)(vendor|third_party|thirdparty|external)\//,
    why: "vendored upstream sources (Go, PHP, C++ convention)",
  },
  {
    pattern: /(^|\/)(bower_components|jspm_packages)\//,
    why: "legacy JS dependency trees",
  },
  {
    pattern: /(^|\/)(Pods|Carthage)\//,
    why: "CocoaPods / Carthage dependency checkouts",
  },
  {
    pattern: /(^|\/)(\.venv|venv|site-packages)\//,
    why: "Python virtualenv vendored into the tree",
  },

  // --- Lockfiles ----------------------------------------------------------
  // A lockfile changes on every `install`. It is a machine-written manifest,
  // and crediting its format (JSON/YAML/TOML) as a skill is meaningless.
  {
    pattern:
      /(^|\/)(package-lock\.json|npm-shrinkwrap\.json|yarn\.lock|pnpm-lock\.yaml|bun\.lockb?|Cargo\.lock|composer\.lock|Gemfile\.lock|poetry\.lock|Pipfile\.lock|go\.sum|mix\.lock|packages\.lock\.json|gradle\.lockfile|Podfile\.lock|pubspec\.lock|flake\.lock)$/,
    why: "lockfile — regenerated by a package manager, not written by a human",
  },

  // --- Build output -------------------------------------------------------
  {
    pattern: /(^|\/)(dist|build|out|target|bin|obj)\//,
    why: "compiler / bundler output",
  },
  {
    pattern: /(^|\/)(\.next|\.nuxt|\.svelte-kit|\.output|\.turbo|\.parcel-cache)\//,
    why: "framework build caches",
  },
  {
    pattern: /(^|\/)(coverage|__pycache__|\.pytest_cache|\.mypy_cache)\//,
    why: "tooling caches and coverage reports",
  },
  { pattern: /(^|\/)\.terraform\//, why: "downloaded Terraform providers" },

  // --- Minified / bundled artefacts ---------------------------------------
  {
    pattern: /\.min\.(js|mjs|cjs|css)$/,
    why: "minified bundle — machine output of source that lives elsewhere",
  },
  {
    pattern: /\.(bundle|chunk)\.(js|mjs|cjs|css)$/,
    why: "bundler artefact",
  },
  { pattern: /\.map$/, why: "source map — generated" },

  // --- Generated code -----------------------------------------------------
  {
    pattern: /\.pb\.(go|cc|h|rb|ts|js)$/,
    why: "protobuf codegen",
  },
  {
    pattern: /_pb2(_grpc)?\.pyi?$/,
    why: "protobuf / gRPC codegen (Python)",
  },
  {
    pattern: /(_pb|_grpc\.pb)\.(js|ts|swift|java)$/,
    why: "protobuf / gRPC codegen",
  },
  {
    pattern: /(\.|_)(generated|gen)\.[a-z0-9]+$/i,
    why: "conventionally named generated file",
  },
  {
    pattern: /\.(g|freezed)\.dart$/,
    why: "Dart build_runner codegen",
  },
  {
    pattern: /\.designer\.cs$/,
    why: "Visual Studio designer codegen",
  },
  {
    pattern: /(^|\/)(generated|__generated__|gen)\//,
    why: "directory conventionally holding codegen output",
  },
  {
    pattern: /(^|\/)__snapshots__\//,
    why: "test snapshots — recorded, not written",
  },
  {
    pattern: /(^|\/)drizzle\/meta\//,
    why: "Drizzle migration journal — machine-maintained",
  },
];

/**
 * True when a changed file must not contribute a technology tag.
 * Backslashes are normalised so a Windows-style path cannot slip past the
 * directory patterns.
 */
export function isGeneratedOrVendored(path: string): boolean {
  const normalized = path.replace(/\\/g, "/");
  return EXCLUDED_PATH_PATTERNS.some(({ pattern }) => pattern.test(normalized));
}

/**
 * Extension → normalized technology tag.
 *
 * Deliberately conservative: extensions that are ambiguous about *skill* (`.md`,
 * `.txt`, `.csv`, images, fonts, binaries) are simply absent, so they credit
 * nothing. Tags are lowercase and stable — they are what a profile displays and
 * what aggregates across users, so renaming one is a breaking change.
 */
export const EXTENSION_TECHNOLOGY: Readonly<Record<string, string>> = {
  ts: "typescript",
  tsx: "typescript",
  mts: "typescript",
  cts: "typescript",
  js: "javascript",
  jsx: "javascript",
  mjs: "javascript",
  cjs: "javascript",
  vue: "vue",
  svelte: "svelte",
  astro: "astro",
  py: "python",
  rb: "ruby",
  go: "go",
  rs: "rust",
  java: "java",
  kt: "kotlin",
  kts: "kotlin",
  scala: "scala",
  swift: "swift",
  m: "objective-c",
  mm: "objective-c",
  c: "c",
  h: "c",
  cc: "cpp",
  cpp: "cpp",
  cxx: "cpp",
  hpp: "cpp",
  cs: "csharp",
  php: "php",
  ex: "elixir",
  exs: "elixir",
  erl: "erlang",
  hs: "haskell",
  clj: "clojure",
  dart: "dart",
  lua: "lua",
  r: "r",
  jl: "julia",
  zig: "zig",
  sh: "shell",
  bash: "shell",
  zsh: "shell",
  fish: "shell",
  ps1: "powershell",
  sql: "sql",
  css: "css",
  scss: "sass",
  sass: "sass",
  less: "less",
  html: "html",
  htm: "html",
  graphql: "graphql",
  gql: "graphql",
  proto: "protobuf",
  tf: "terraform",
  tfvars: "terraform",
  hcl: "hcl",
  nix: "nix",
  sol: "solidity",
  ipynb: "jupyter",
};

/**
 * Whole filenames that identify a technology without an extension. Kept
 * separate from the extension map because these are matched on the basename,
 * not on what follows the last dot.
 */
export const FILENAME_TECHNOLOGY: Readonly<Record<string, string>> = {
  dockerfile: "docker",
  "docker-compose.yml": "docker",
  "docker-compose.yaml": "docker",
  makefile: "make",
  "cmakelists.txt": "cmake",
  gemfile: "ruby",
  rakefile: "ruby",
  "cargo.toml": "rust",
  "go.mod": "go",
  "pyproject.toml": "python",
  "requirements.txt": "python",
  "build.gradle": "gradle",
  "build.gradle.kts": "gradle",
  "pom.xml": "maven",
};

/** The technology a single changed file credits, or null for "nothing". */
export function technologyForPath(path: string): string | null {
  if (isGeneratedOrVendored(path)) return null;

  const normalized = path.replace(/\\/g, "/");
  const basename = (normalized.split("/").pop() ?? "").toLowerCase();
  if (!basename) return null;

  const byName = FILENAME_TECHNOLOGY[basename];
  if (byName) return byName;

  // `Dockerfile.prod` / `Dockerfile.dev` are still Dockerfiles.
  if (basename.startsWith("dockerfile.")) return "docker";

  const dot = basename.lastIndexOf(".");
  if (dot <= 0) return null;
  const extension = basename.slice(dot + 1);
  return EXTENSION_TECHNOLOGY[extension] ?? null;
}

/** The API caps a single event's technology list; see `technologyTagSchema`. */
export const MAX_TECHNOLOGIES_PER_EVENT = 30;

/**
 * The distinct technologies a set of changed files credits, sorted so the same
 * commit always produces byte-identical output (which is what lets a user
 * diff two extractor runs and see nothing changed).
 */
export function inferTechnologies(paths: readonly string[]): string[] {
  const tags = new Set<string>();
  for (const path of paths) {
    const tag = technologyForPath(path);
    if (tag) tags.add(tag);
  }
  return [...tags].sort().slice(0, MAX_TECHNOLOGIES_PER_EVENT);
}
