export const DEFAULT_SKILLS = [
  "TypeScript",
  "JavaScript",
  "Node.js",
  "Express",
  "Fastify",
  "NestJS",
  "Next.js",
  "React",
  "Vue.js",
  "Angular",
  "Svelte",
  "Nuxt",
  "Remix",
  "Vite",
  "Redux",
  "Zustand",
  "TanStack Query",
  "Tailwind CSS",
  "Styled Components",
  "Webpack",
  "Babel",
  "Jest",
  "Vitest",
  "Playwright",
  "Cypress",
  "Storybook",
  "HTML5",
  "CSS3",
  "Sass",
  "React Native",
  "Flutter",
  "Dart",
  "Swift",
  "SwiftUI",
  "Kotlin",
  "Jetpack Compose",
  "Java",
  "Spring Boot",
  "Spring Cloud",
  "Hibernate",
  "Micronaut",
  "Quarkus",
  "C#",
  ".NET",
  "ASP.NET Core",
  "Entity Framework",
  "MediatR",
  "Python",
  "FastAPI",
  "Django",
  "Flask",
  "Pydantic",
  "Pandas",
  "NumPy",
  "PyTorch",
  "TensorFlow",
  "scikit-learn",
  "Airflow",
  "dbt",
  "Spark",
  "Go",
  "Gin",
  "Fiber",
  "gRPC",
  "Rust",
  "Actix",
  "Axum",
  "Tokio",
  "C++",
  "Qt",
  "Boost",
  "PHP",
  "Laravel",
  "Symfony",
  "WordPress",
  "Ruby",
  "Ruby on Rails",
  "Elixir",
  "Phoenix",
  "Scala",
  "Akka",
  "Kafka",
  "RabbitMQ",
  "NATS",
  "Redis",
  "PostgreSQL",
  "MySQL",
  "MariaDB",
  "SQL Server",
  "Oracle",
  "SQLite",
  "MongoDB",
  "DynamoDB",
  "Cassandra",
  "ElasticSearch",
  "OpenSearch",
  "Neo4j",
  "Supabase",
  "Prisma",
  "Drizzle ORM",
  "TypeORM",
  "GraphQL",
  "Apollo",
  "REST API",
  "OpenAPI",
  "WebSockets",
  "Socket.IO",
  "OAuth2",
  "JWT",
  "Keycloak",
  "Auth0",
  "Docker",
  "Kubernetes",
  "Helm",
  "Terraform",
  "Pulumi",
  "Ansible",
  "Istio",
  "NGINX",
  "Traefik",
  "Prometheus",
  "Grafana",
  "Loki",
  "Datadog",
  "OpenTelemetry",
  "Sentry",
  "AWS",
  "Azure",
  "Google Cloud",
  "Cloudflare",
  "CI/CD",
  "GitHub Actions",
  "GitLab CI",
  "Jenkins",
  "ArgoCD",
  "Linux",
  "Bash",
  "PowerShell",
  "Serverless",
  "AWS Lambda",
  "Cloud Run",
  "Event-Driven Architecture",
  "Microservices",
  "Monolith",
  "Hexagonal Architecture",
  "Clean Architecture",
  "DDD",
  "CQRS",
  "Event Sourcing",
  "SOLID",
  "TDD",
  "BDD",
  "OWASP",
  "Penetration Testing",
  "Performance Tuning",
  "Load Testing",
  "k6",
  "Locust",
  "Selenium",
  "Pact",
  "Contract Testing",
  "Feature Flags",
  "LaunchDarkly",
  "Internationalization",
  "Accessibility",
  "Figma",
  "Design Systems",
  "Product Analytics",
  "Amplitude",
  "Segment",
  "Snowflake",
  "BigQuery",
  "Redshift",
  "ClickHouse",
  "Trino",
  "Presto",
  "MLflow",
  "Kubeflow",
  "LangChain",
  "RAG",
  "Vector Databases",
  "FAISS",
  "Pinecone",
  "Weaviate",
  "MLOps",
  "Computer Vision",
  "NLP",
  "Time Series",
  "MATLAB",
  "R",
  "Shiny",
  "Tableau",
  "Power BI",
  "Looker",
] as const;

export const DEFAULT_TITLES = [
  "Software Engineer",
  "Backend Engineer",
  "Frontend Engineer",
  "Full Stack Engineer",
  "Platform Engineer",
  "DevOps Engineer",
  "Site Reliability Engineer",
  "Cloud Engineer",
  "Data Engineer",
  "Data Scientist",
  "Machine Learning Engineer",
  "AI Engineer",
  "MLOps Engineer",
  "QA Engineer",
  "Automation Engineer",
  "Security Engineer",
  "Application Security Engineer",
  "Staff Engineer",
  "Principal Engineer",
  "Tech Lead",
  "Engineering Manager",
  "Solutions Architect",
  "Software Architect",
  "Mobile Engineer",
  "iOS Engineer",
  "Android Engineer",
  "Game Developer",
  "Embedded Engineer",
  "Systems Engineer",
  "Infrastructure Engineer",
  "Observability Engineer",
  "Release Engineer",
  "Build Engineer",
  "Database Engineer",
  "BI Engineer",
  "Analytics Engineer",
  "Prompt Engineer",
  "NLP Engineer",
  "Computer Vision Engineer",
  "Robotics Engineer",
  "Blockchain Engineer",
  "Web3 Engineer",
  "Rust Engineer",
  "Go Engineer",
  "Java Engineer",
  ".NET Engineer",
  "Python Engineer",
  "Node.js Engineer",
  "React Developer",
  "Vue Developer",
  "Angular Developer",
  "Kotlin Developer",
  "Swift Developer",
  "PHP Developer",
  "Ruby Developer",
  "Elixir Developer",
  "SRE Manager",
  "Data Platform Engineer",
  "Search Engineer",
  "API Engineer",
  "Integration Engineer",
  "Systems Analyst",
  "Technical Consultant",
  "Technical Program Manager",
  "Engineering Director",
  "Head of Engineering",
  "Chief Architect",
  "Reliability Architect",
  "Data Platform Architect",
  "AI Platform Engineer",
  "Infrastructure Architect",
] as const;

export function normalizeCatalogName(value: string): string {
  return value.trim().toLowerCase();
}
