export const DEFAULT_SKILLS = [
  "TypeScript",
  "JavaScript",
  "Node.js",
  "Express",
  "Fastify",
  "NestJS",
  "Next.js",
  "React",
  "Vue.js",
  "Angular",
  "Svelte",
  "Nuxt",
  "Remix",
  "Vite",
  "Redux",
  "Zustand",
  "TanStack Query",
  "Tailwind CSS",
  "Styled Components",
  "Webpack",
  "Babel",
  "Jest",
  "Vitest",
  "Playwright",
  "Cypress",
  "Storybook",
  "HTML5",
  "CSS3",
  "Sass",
  "React Native",
  "Flutter",
  "Dart",
  "Swift",
  "SwiftUI",
  "Kotlin",
  "Jetpack Compose",
  "Java",
  "Spring Boot",
  "Spring Cloud",
  "Hibernate",
  "Micronaut",
  "Quarkus",
  "C#",
  ".NET",
  "ASP.NET Core",
  "Entity Framework",
  "MediatR",
  "Python",
  "FastAPI",
  "Django",
  "Flask",
  "Pydantic",
  "Pandas",
  "NumPy",
  "PyTorch",
  "TensorFlow",
  "scikit-learn",
  "Airflow",
  "dbt",
  "Spark",
  "Go",
  "Gin",
  "Fiber",
  "gRPC",
  "Rust",
  "Actix",
  "Axum",
  "Tokio",
  "C++",
  "Qt",
  "Boost",
  "PHP",
  "Laravel",
  "Symfony",
  "WordPress",
  "Ruby",
  "Ruby on Rails",
  "Elixir",
  "Phoenix",
  "Scala",
  "Akka",
  "Kafka",
  "RabbitMQ",
  "NATS",
  "Redis",
  "PostgreSQL",
  "MySQL",
  "MariaDB",
  "SQL Server",
  "Oracle",
  "SQLite",
  "MongoDB",
  "DynamoDB",
  "Cassandra",
  "ElasticSearch",
  "OpenSearch",
  "Neo4j",
  "Supabase",
  "Prisma",
  "Drizzle ORM",
  "TypeORM",
  "GraphQL",
  "Apollo",
  "REST API",
  "OpenAPI",
  "WebSockets",
  "Socket.IO",
  "OAuth2",
  "JWT",
  "Keycloak",
  "Auth0",
  "Docker",
  "Kubernetes",
  "Helm",
  "Terraform",
  "Pulumi",
  "Ansible",
  "Istio",
  "NGINX",
  "Traefik",
  "Prometheus",
  "Grafana",
  "Loki",
  "Datadog",
  "OpenTelemetry",
  "Sentry",
  "AWS",
  "Azure",
  "Google Cloud",
  "Cloudflare",
  "CI/CD",
  "GitHub Actions",
  "GitLab CI",
  "Jenkins",
  "ArgoCD",
  "Linux",
  "Bash",
  "PowerShell",
  "Serverless",
  "AWS Lambda",
  "Cloud Run",
  "Event-Driven Architecture",
  "Microservices",
  "Monolith",
  "Hexagonal Architecture",
  "Clean Architecture",
  "DDD",
  "CQRS",
  "Event Sourcing",
  "SOLID",
  "TDD",
  "BDD",
  "OWASP",
  "Penetration Testing",
  "Performance Tuning",
  "Load Testing",
  "k6",
  "Locust",
  "Selenium",
  "Pact",
  "Contract Testing",
  "Feature Flags",
  "LaunchDarkly",
  "Internationalization",
  "Accessibility",
  "Figma",
  "Design Systems",
  "Product Analytics",
  "Amplitude",
  "Segment",
  "Snowflake",
  "BigQuery",
  "Redshift",
  "ClickHouse",
  "Trino",
  "Presto",
  "MLflow",
  "Kubeflow",
  "LangChain",
  "RAG",
  "Vector Databases",
  "FAISS",
  "Pinecone",
  "Weaviate",
  "MLOps",
  "Computer Vision",
  "NLP",
  "Time Series",
  "MATLAB",
  "R",
  "Shiny",
  "Tableau",
  "Power BI",
  "Looker",
  // --- Product Design / UX / UI ---
  "Sketch",
  "Adobe XD",
  "Framer",
  "InVision",
  "Zeplin",
  "Adobe Photoshop",
  "Adobe Illustrator",
  "Adobe After Effects",
  "Miro",
  "FigJam",
  "Whimsical",
  "User Research",
  "Usability Testing",
  "Heuristic Evaluation",
  "Wireframing",
  "Prototyping",
  "Interaction Design",
  "Visual Design",
  "Motion Design",
  "UX Writing",
  "Content Design",
  "Information Architecture",
  "Design Thinking",
  "Design Tokens",
  "Journey Mapping",
  "Service Design",
  "Brand Design",
  // --- Product Management / Ownership ---
  "Product Strategy",
  "Product Discovery",
  "Roadmapping",
  "Prioritization",
  "OKRs",
  "Stakeholder Management",
  "Go-to-Market",
  "Market Research",
  "Competitive Analysis",
  "Customer Interviews",
  "User Stories",
  "Story Mapping",
  "Backlog Management",
  "Sprint Planning",
  "Agile",
  "Scrum",
  "Kanban",
  "SAFe",
  "Jira",
  "Confluence",
  "Productboard",
  "Aha!",
  "A/B Testing",
  "Experimentation",
  // --- QA / Test ---
  "Quality Assurance",
  "Test Automation",
  "Test Planning",
  "Test Strategy",
  "Test Case Design",
  "Manual Testing",
  "Exploratory Testing",
  "Regression Testing",
  "API Testing",
  "Postman",
  "TestRail",
  "Xray",
  "Appium",
  "Cucumber",
  "Gherkin",
  "JMeter",
  "SoapUI",
  "Bug Tracking",
  // --- Data (analyst / scientist / engineer) ---
  "SQL",
  "Data Analysis",
  "Data Visualization",
  "Data Modeling",
  "Data Warehousing",
  "ETL",
  "ELT",
  "Statistics",
  "Excel",
  "Google Analytics",
  "Looker Studio",
  "Metabase",
  "Superset",
  "Databricks",
  "Fivetran",
  "Great Expectations",
  "Data Governance",
  "Jupyter",
  "Matplotlib",
  "Seaborn",
  "Plotly",
  "SciPy",
  "Hadoop",
  "Hive",
  "Machine Learning",
  "Deep Learning",
  // --- DevOps / SRE / Platform ---
  "GitOps",
  "HashiCorp Vault",
  "Consul",
  "Packer",
  "CloudFormation",
  "Kustomize",
  "ELK Stack",
  "Fluentd",
  "PagerDuty",
  "New Relic",
  "Splunk",
  "SonarQube",
  "Artifactory",
  "Spinnaker",
  "CircleCI",
  "TeamCity",
  "Podman",
  "Linkerd",
  "Service Mesh",
  "SLO/SLI",
  "Incident Management",
  "Chaos Engineering",
  "Capacity Planning",
] as const;

export const DEFAULT_TITLES = [
  "Software Engineer",
  "Backend Engineer",
  "Frontend Engineer",
  "Full Stack Engineer",
  "Platform Engineer",
  "DevOps Engineer",
  "Site Reliability Engineer",
  "Cloud Engineer",
  "Data Engineer",
  "Data Scientist",
  "Machine Learning Engineer",
  "AI Engineer",
  "MLOps Engineer",
  "QA Engineer",
  "Automation Engineer",
  "Security Engineer",
  "Application Security Engineer",
  "Staff Engineer",
  "Principal Engineer",
  "Tech Lead",
  "Engineering Manager",
  "Solutions Architect",
  "Software Architect",
  "Mobile Engineer",
  "iOS Engineer",
  "Android Engineer",
  "Game Developer",
  "Embedded Engineer",
  "Systems Engineer",
  "Infrastructure Engineer",
  "Observability Engineer",
  "Release Engineer",
  "Build Engineer",
  "Database Engineer",
  "BI Engineer",
  "Analytics Engineer",
  "Prompt Engineer",
  "NLP Engineer",
  "Computer Vision Engineer",
  "Robotics Engineer",
  "Blockchain Engineer",
  "Web3 Engineer",
  "Rust Engineer",
  "Go Engineer",
  "Java Engineer",
  ".NET Engineer",
  "Python Engineer",
  "Node.js Engineer",
  "React Developer",
  "Vue Developer",
  "Angular Developer",
  "Kotlin Developer",
  "Swift Developer",
  "PHP Developer",
  "Ruby Developer",
  "Elixir Developer",
  "SRE Manager",
  "Data Platform Engineer",
  "Search Engineer",
  "API Engineer",
  "Integration Engineer",
  "Systems Analyst",
  "Technical Consultant",
  "Technical Program Manager",
  "Engineering Director",
  "Head of Engineering",
  "Chief Architect",
  "Reliability Architect",
  "Data Platform Architect",
  "AI Platform Engineer",
  "Infrastructure Architect",
  // --- Product Design / UX / UI ---
  "Product Designer",
  "UX Designer",
  "UI Designer",
  "UX/UI Designer",
  "UX Researcher",
  "Interaction Designer",
  "Visual Designer",
  "Motion Designer",
  "Service Designer",
  "Brand Designer",
  "Design Systems Designer",
  "UX Writer",
  "Content Designer",
  "Product Design Lead",
  "Design Lead",
  "Design Manager",
  "Head of Design",
  // --- Product Management ---
  "Product Manager",
  "Associate Product Manager",
  "Senior Product Manager",
  "Group Product Manager",
  "Principal Product Manager",
  "Technical Product Manager",
  "Growth Product Manager",
  "Platform Product Manager",
  "Product Lead",
  "Director of Product",
  "Head of Product",
  "VP of Product",
  "Chief Product Officer",
  // --- Product Ownership / Agile ---
  "Product Owner",
  "Senior Product Owner",
  "Technical Product Owner",
  "Scrum Master",
  "Agile Coach",
  "Business Analyst",
  // --- QA / Test ---
  "QA Analyst",
  "QA Lead",
  "QA Manager",
  "Test Engineer",
  "Test Analyst",
  "Test Lead",
  "SDET",
  "QA Automation Engineer",
  "Manual QA Engineer",
  "Quality Engineer",
  // --- Data (analyst / scientist / engineer) ---
  "Data Analyst",
  "Senior Data Analyst",
  "Business Intelligence Analyst",
  "Product Analyst",
  "Marketing Analyst",
  "Quantitative Analyst",
  "Research Scientist",
  "Applied Scientist",
  "Analytics Manager",
  "Data Science Manager",
  "Head of Data",
  // --- DevOps / SRE / Platform ---
  "DevOps Lead",
  "DevSecOps Engineer",
  "Cloud Architect",
  "DevOps Architect",
  "Kubernetes Administrator",
  "Systems Administrator",
  "Release Manager",
] as const;

export function normalizeCatalogName(value: string): string {
  return value.trim().toLowerCase();
}
