import type { Post, PostSource, PostStatus } from "@repo/schemas";
import { BADGE } from "../../../shared-components/surface";

// Tones come from the shared `BADGE` map rather than per-file literals. These
// used to be hand-rolled here, in `StatusBadge` (settings) and in
// `describeMatch` (search) with three different definitions of "success", so a
// "Current" work-history chip and an "Active" token chip rendered as visibly
// different greens in dark mode.
export const SOURCE_META: Record<
  PostSource,
  { label: string; className: string }
> = {
  manual: { label: "Manual", className: BADGE.neutral },
  mcp: { label: "MCP", className: BADGE.info },
  // Not `BADGE.accent`: violet is the default `--profile-accent`, so an
  // accent-coloured source badge collides with the user's profile theme.
  agent: { label: "Agent", className: BADGE.magenta },
  commit: { label: "Commit", className: BADGE.warning },
};

export const STATUS_META: Record<
  PostStatus,
  { label: string; className: string }
> = {
  draft: { label: "Draft", className: BADGE.neutral },
  // Amber, not neutral: a post waiting on the author is an action item, and it
  // has to read differently from a draft they chose to park.
  pending_review: { label: "Pending review", className: BADGE.warning },
  published: { label: "Published", className: BADGE.success },
};

/**
 * The review queue's contents: posts waiting on the author, newest first.
 *
 * Lives here rather than in the page so the posts page can count the same set
 * it links to — a badge that disagrees with the queue is worse than no badge.
 * `createdAt` is a `Date` off the schema, but is re-wrapped defensively because
 * a cached/serialised list can hand back the ISO string.
 */
export function selectPendingReview(posts: readonly Post[]): Post[] {
  return posts
    .filter((post) => post.status === "pending_review")
    .sort(
      (a, b) =>
        new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime(),
    );
}

/**
 * A post the user did not type themselves.
 *
 * Mirrors the server rule in `assertMachineAuthoredPostIsImmutable`: anything
 * that isn't `manual` has immutable content, so the UI must not offer an edit
 * affordance for it. This is a mirror, never the enforcement — the API rejects
 * the PATCH regardless of what the UI shows.
 */
export function isMachineAuthored(source: PostSource): boolean {
  return source !== "manual";
}

/** The one-line reason a machine-authored post has no Edit button. */
export const IMMUTABLE_POST_REASON =
  "Written by software and published exactly as generated — locking the text is what makes it verifiable, so you can approve it or delete it, but not edit it.";

/**
 * Where a post came from, in the author's own terms.
 *
 * `metadata.repo` sharpens the sentence when the commit flow supplied it
 * ("from your commits in linkhub-v.1"), because "some automated tool wrote
 * this" is not enough for someone deciding whether to make it public.
 */
export function describePostProvenance(post: Pick<Post, "source" | "metadata">): string {
  const repo = readMetadataString(post.metadata, "repo");

  switch (post.source) {
    case "commit":
      return repo
        ? `Generated from your commit activity in ${repo}`
        : "Generated from your commit activity";
    case "mcp":
      return repo
        ? `Generated by a connected AI tool working in ${repo}`
        : "Generated by a connected AI tool";
    case "agent":
      return "Generated by an agent acting on your behalf";
    case "manual":
      return "Written by you";
  }
}

function readMetadataString(
  metadata: Post["metadata"],
  key: string,
): string | null {
  const value = metadata?.[key];
  return typeof value === "string" && value.trim().length > 0
    ? value.trim()
    : null;
}

export type PostMetadataFact = { key: string; label: string; value: string };

/**
 * Labels for the keys the MCP commit flow actually writes. Anything else a
 * source stuffs into `metadata` is still shown — with its raw key as the label
 * — because hiding a fact the post is claiming to be based on is worse than an
 * ugly label.
 */
const METADATA_LABELS: Record<string, string> = {
  repo: "Repository",
  commitCount: "Commits",
  period: "Period",
};

/** Ordered so the commit flow's three keys read the same way every time. */
const METADATA_ORDER = ["repo", "commitCount", "period"];

export function postMetadataFacts(
  metadata: Post["metadata"],
): PostMetadataFact[] {
  if (!metadata) {
    return [];
  }

  const keys = Object.keys(metadata).sort((a, b) => {
    const rankA = METADATA_ORDER.indexOf(a);
    const rankB = METADATA_ORDER.indexOf(b);
    if (rankA === -1 && rankB === -1) {
      return a.localeCompare(b);
    }
    return (rankA === -1 ? Number.MAX_SAFE_INTEGER : rankA) -
      (rankB === -1 ? Number.MAX_SAFE_INTEGER : rankB);
  });

  return keys.flatMap((key) => {
    const value = metadata[key];
    // `metadata` is typed `Record<string, unknown>` on the wire; the schema
    // caps it at string | number | boolean. Skip anything else rather than
    // rendering "[object Object]".
    if (
      typeof value !== "string" &&
      typeof value !== "number" &&
      typeof value !== "boolean"
    ) {
      return [];
    }
    const text = String(value).trim();
    if (text.length === 0) {
      return [];
    }
    return [{ key, label: METADATA_LABELS[key] ?? key, value: text }];
  });
}

export function formatPostDate(date: Date | string | null): string {
  if (!date) {
    return "";
  }
  const value = typeof date === "string" ? new Date(date) : date;
  if (Number.isNaN(value.getTime())) {
    return "";
  }
  return value.toLocaleDateString(undefined, {
    year: "numeric",
    month: "short",
    day: "numeric",
  });
}
